export type CareAge = 'baby' | 'toddler' | 'preschool' | 'bigkid' | 'tween' | 'multiple';
export type CareEnergy = 'high' | 'some' | 'exhausted';

export type CaregiverPlan = {
  title: string;
  context: string;
  doThisFirst: string;
  whatToSay: string;
  timelineLabel: string;
  steps: string[];
  planB: string;
  avoid: string;
  finish: string;
  childNote?: string;
};

type Scenario = {
  title: string;
  immediate: string;
  say: string;
  activities: Record<'baby' | 'little' | 'older' | 'multiple', string[]>;
  planB: string;
  avoid: string;
  finish: string;
};

const scenarios: Record<string, Scenario> = {
  bored: { title: 'A boredom plan', immediate: 'Choose one activity and set it up with only the materials it needs.', say: 'You do not need me to entertain you. Choose this or help me choose one other idea.', activities: { baby: ['Put baby on a floor mat with two safe objects and sit within reach.', 'Switch positions or rooms when interest fades.'], little: ['Offer blocks, painter’s tape roads, or water painting with a brush and cup.', 'Join for two minutes, then say what you will do nearby.'], older: ['Offer a choice: build something from recycling, draw a comic, or make a scavenger hunt.', 'Let them own the setup and cleanup.'], multiple: ['Choose one shared open-ended activity such as blocks, blanket forts, or sidewalk chalk.', 'Give each child a separate job or material to reduce competition.'] }, planB: 'Change one thing: location, materials, or whether you join for two minutes. Do not offer a long menu.', avoid: 'Do not keep producing new entertainment every few minutes.', finish: 'Give a clear cleanup warning and let them save or photograph unfinished work.' },
  fighting: { title: 'Stop the fight and reset', immediate: 'Move close, block hitting or grabbing, and separate the children into two safe spaces.', say: 'I will not let you hurt each other. We will solve this when bodies are calm.', activities: { baby: ['Move baby out of reach and check for injury.', 'Give the older child a separate calm task while you settle baby.'], little: ['Give each child a different simple activity in a different spot.', 'After calm, hear one sentence from each child and decide the next turn.'], older: ['Send each child to a separate reset spot with a book, drawing, or music.', 'After calm, ask each what they need and have them propose one fair next step.'], multiple: ['Separate first; do not investigate while anyone is unsafe.', 'Use different rooms or clearly divided zones and rotate shared items later.'] }, planB: 'Keep them separated longer and remove the disputed item. Resolution can wait; safety cannot.', avoid: 'Do not demand apologies, decide who is “bad,” or lecture while they are flooded.', finish: 'Practice the replacement phrase—“Stop,” “My turn next,” or “I need help”—once everyone is calm.' },
  meltdown: { title: 'Get through the meltdown', immediate: 'Make the space safe, lower lights and noise, and use very few words. Stay close without crowding.', say: 'You are safe. I am here. We will talk when your body is calmer.', activities: { baby: ['Check feeding, diaper, temperature, pain, and tiredness.', 'Try one familiar soothing method: hold, sway, shush, or a quiet song.'], little: ['Offer a quiet corner, cuddle if welcomed, or one familiar calm song.', 'When breathing slows, offer water and one tiny next step.'], older: ['Reduce the audience and offer space, headphones, drawing, or quiet music.', 'Reconnect privately; solve the trigger after regulation returns.'], multiple: ['Move other children to a safe activity or another room.', 'Focus on the overwhelmed child while keeping your voice low for everyone.'] }, planB: 'If closeness escalates them, stay visible and give more space. If anyone is unsafe, get another adult or emergency help.', avoid: 'Do not reason, threaten consequences, ask many questions, or force eye contact during the peak.', finish: 'Offer water or a snack, reconnect briefly, and lower the next demand.' },
  'burn-energy': { title: 'Safe movement that fits the window', immediate: 'Clear a safe movement space and state the stop signal before starting.', say: 'Your body needs to move. We are going to move safely, then slow down.', activities: { baby: ['Do floor play: reaching, rolling, crawling toward a toy, or supported dancing.', 'Alternate active floor play with a cuddle or feed/rest cue.'], little: ['Try animal walks, a hallway obstacle path, dance-and-freeze, or outside running.', 'End with two slow songs, stretching, or a drink of water.'], older: ['Choose a brisk walk, dance challenge, ball play, bike ride, or timed movement circuit.', 'Let them help choose intensity and lead one round.'], multiple: ['Use dance-and-freeze, relay jobs, a playground, or a simple obstacle course.', 'Avoid elimination games; everyone keeps moving.'] }, planB: 'If outdoor play is not possible, use music, stairs with supervision, animal walks, or ten rounds of move-and-freeze indoors.', avoid: 'Do not choose rough play beside furniture or high-energy play right before sleep.', finish: 'Use a clear final round, water, and a calm transition activity.' },
  quiet: { title: 'A genuinely quiet activity', immediate: 'Dim the environment and offer one contained, low-noise activity.', say: 'It is quiet time. You can choose this activity or rest beside me.', activities: { baby: ['Look at board books, listen to a soft song, or explore two sensory-safe objects on a mat.', 'Keep baby close and follow sleepy or hungry cues.'], little: ['Try sticker paper, Water Wow, reusable drawing, board books, puzzles, or a calm audio story.', 'Use a tray or small basket so the activity stays contained.'], older: ['Offer reading, coloring, Lego, a puzzle, journaling, or an audiobook with drawing.', 'Let them use headphones if that helps them settle.'], multiple: ['Give each child their own quiet bin, book stack, or drawing surface.', 'Seat them apart enough that materials do not become a conflict.'] }, planB: 'If sitting still is failing, try a slow stroller walk, bath play, or a quiet music-and-stretch break.', avoid: 'Avoid running games, loud toys, screens that wind them up, or an elaborate craft with heavy cleanup.', finish: 'Give a two-minute warning, then put the quiet materials back together.' },
  lunch: { title: 'Get lunch served', immediate: 'Serve a simple meal with one familiar food; lunch does not need to be impressive.', say: 'This is lunch. You choose what and how much to eat from what is here.', activities: { baby: ['Use the baby’s usual milk/feeding plan and age-appropriate food; stay seated and attentive.', 'Follow hunger and fullness cues.'], little: ['Try a divided plate: toast or quesadilla, fruit, and yogurt/cheese or another familiar protein.', 'Let them carry napkins or choose between two fruits.'], older: ['Offer a sandwich/wrap, fruit, and yogurt or vegetables; invite them to assemble it.', 'Keep the meal time-limited and neutral.'], multiple: ['Build one shared snack-plate lunch with familiar components.', 'Give each child one safe choice, not a separate custom meal.'] }, planB: 'Use a backup meal—toast, yogurt, fruit, cheese, leftovers, or a simple sandwich—and move on.', avoid: 'Do not pressure bites, bargain with dessert, or cook several separate meals.', finish: 'Clear lunch calmly and note what needs restocking.' },
  snack: { title: 'A quick, steadying snack', immediate: 'Offer water and a familiar snack with carbohydrate plus protein or fat.', say: 'Here is snack. You may choose from what is here.', activities: { baby: ['Use the baby’s normal milk/feeding plan and only developmentally safe solids.', 'Seat and supervise baby while eating.'], little: ['Try banana and yogurt, crackers and cheese, toast with seed/nut butter as safe, or fruit and hummus.', 'Sit for the snack rather than grazing while running.'], older: ['Offer fruit plus yogurt, cheese and crackers, hummus and pita, or toast with a safe spread.', 'Let them prepare one part independently.'], multiple: ['Serve the same two or three components family-style.', 'Pre-divide a highly desired item to avoid a new conflict.'] }, planB: 'If choices cause a stall, offer one reliable option and save the next meal for the normal time.', avoid: 'Avoid choking hazards, unsupervised eating for young children, or turning refusal into a negotiation.', finish: 'Put cups and dishes away and preview what comes next.' },
  bedtime: { title: 'Move toward sleep now', immediate: 'Lower lights, stop screens and active play, and begin the shortest familiar bedtime routine.', say: 'It is time for sleep. We will do pajamas, one book, then bed.', activities: { baby: ['Check feed, diaper, temperature, and discomfort, then use the usual safe-sleep routine.', 'Keep the room dark and interaction quiet.'], little: ['Do toilet/diaper, pajamas, one book, one song, and bed in the same order.', 'Use one boring walk-back phrase if they get up.'], older: ['Set devices outside the room, finish hygiene, then allow brief reading in dim light.', 'Agree on one final check-in rather than repeated requests.'], multiple: ['Start the youngest first or give the older child a quiet independent step.', 'Keep each child’s routine predictable without trying to settle everyone at once.'] }, planB: 'Return to the last familiar step and make your response brief and boring. Address patterns tomorrow, not in a 3 AM negotiation.', avoid: 'Do not add unlimited requests, bright lights, screens, or a brand-new sleep strategy tonight.', finish: 'Once everyone is safe in their sleep space, keep later checks quiet and consistent.' },
  leaving: { title: 'Get out the door', immediate: 'Name the one thing that must happen next and physically gather essentials now.', say: 'We are leaving. Shoes first. You may choose the blue shoes or the red shoes.', activities: { baby: ['Check diaper, feed if due, secure baby safely, and grab the packed essentials.', 'Keep one comfort item accessible.'], little: ['Use one-step directions: shoes, then coat, then door.', 'Let them carry one safe item or choose between two acceptable options.'], older: ['Give a three-item checklist and a firm departure time.', 'Ask them to own one job such as water bottles or locking up.'], multiple: ['Assign one job per child and stage everyone at the door.', 'Help the youngest while older children complete their checklist.'] }, planB: 'Drop nonessential tasks, carry or calmly assist a young child if necessary, and leave with the minimum required items.', avoid: 'Do not ask whether they are ready when leaving is not optional or keep adding explanations.', finish: 'Once moving, acknowledge the hard transition and preview where you are going.' },
  'baby-crying': { title: 'Work through baby’s crying', immediate: 'Check breathing and safety, then check hunger, diaper, temperature, pain/illness, and tiredness.', say: 'I am here. I am checking what you need.', activities: { baby: ['Try one soothing method for several minutes: hold, sway, shush, feed if due, or sing softly.', 'If overstimulated, move to a darker, quieter room.'], little: ['Keep siblings nearby with books or a quiet bin while you tend to baby.', 'Explain simply that baby is safe and needs help.'], older: ['Ask an older child for one optional practical job, never responsibility for stopping the crying.', 'Let them move to a quieter room if the sound is overwhelming.'], multiple: ['Put other children in a safe contained activity before focusing on baby.', 'Call another adult if you cannot safely meet everyone’s needs alone.'] }, planB: 'If you are overwhelmed, place baby on their back in a safe empty crib and step away for a few minutes. Never shake a baby.', avoid: 'Do not keep rapidly switching soothing methods or ignore unusual breathing, fever, poor feeding, or lethargy.', finish: 'Contact a healthcare professional for concerning or persistent crying, and urgent care for breathing difficulty or a baby who is hard to wake.' },
  'wont-listen': { title: 'Get cooperation without repeating', immediate: 'Move close, get attention gently, and give one concrete direction with a calm follow-through.', say: 'It is time to do this. You can start, or I will help you start.', activities: { baby: ['Redirect physically and make the safe option easier to reach.', 'Use very few words; babies are not refusing a verbal instruction on purpose.'], little: ['Give one step and one small choice about how—not whether—it happens.', 'Wait five seconds, then calmly help them begin.'], older: ['State the task, deadline, and known consequence once.', 'Ask them to repeat the first step, then step back.'], multiple: ['Address one child by name and one instruction at a time.', 'Do not broadcast repeated directions to the whole room.'] }, planB: 'Reduce the task to the smallest first action and help them start it alongside you.', avoid: 'Avoid shouting from another room, stacking directions, threats, or repeating yourself indefinitely.', finish: 'Notice the cooperation specifically and make the next routine more predictable.' },
  independent: { title: 'Set up independent time', immediate: 'Choose one safe activity the child can manage and define where you will be.', say: 'You can do this here while I work nearby. I will check in when the timer rings.', activities: { baby: ['Use a safe floor space with two or three toys while you remain in sight and actively supervise.', 'Rotate position or one toy; do not rely on containment for a long block.'], little: ['Set out stickers, blocks, magnet tiles, a puzzle, play dough, or a water-paint book.', 'Start together for two minutes, then use a short visual timer.'], older: ['Offer reading, Lego, drawing, a craft kit, a puzzle, or an age-appropriate household project.', 'Agree on when they may interrupt and when you will check in.'], multiple: ['Use separate stations or compatible roles in one activity.', 'Keep coveted supplies duplicated or out of reach.'] }, planB: 'Shorten the timer, move the activity closer to you, or spend two minutes reconnecting before trying again.', avoid: 'Do not expect developmentally unrealistic independence or use an unsafe activity just to buy time.', finish: 'Return when promised and acknowledge what they managed independently.' },
  'one-on-one': { title: 'Make one-on-one time count', immediate: 'Put your phone away and let the child choose one simple connection activity.', say: 'This time is just for us. What should we do together?', activities: { baby: ['Try face-to-face songs, peekaboo, a board book, or floor play.', 'Follow baby’s cues rather than filling every second.'], little: ['Choose pretend play, a book pile, drawing, a short walk, or a favorite song.', 'Let them lead while you narrate and notice.'], older: ['Walk, play a quick game, cook something simple, draw, or talk over a snack.', 'Ask one specific open question and listen.'], multiple: ['If true one-on-one is not possible, give each child a named turn of focused attention.', 'Let the waiting child use a familiar independent activity.'] }, planB: 'If they reject the idea, sit nearby and follow their lead without questions for a few minutes.', avoid: 'Avoid teaching, correcting, multitasking, or turning the time into an interview.', finish: 'Say when you enjoyed it and name when you can connect again.' },
  'just-a-plan': { title: 'A simple care plan', immediate: 'Check immediate needs first: safety, food, diaper/toilet, medication instructions, and rest.', say: 'Here is our plan: needs first, one activity, food or rest, then cleanup.', activities: { baby: ['Feed/diaper as due, do floor play or a stroller walk, then follow sleep cues.', 'Keep the routine close to the family’s usual plan.'], little: ['Start with snack/toilet, choose active or quiet play, then use a five-minute transition warning.', 'Alternate connected play with a short independent block.'], older: ['Agree on food, one activity, responsibilities, and downtime.', 'Let them help shape the order.'], multiple: ['Meet the youngest child’s physical needs, then choose one shared activity.', 'Build separate quiet time into longer care windows.'] }, planB: 'Return to basics: snack or feed, water, toilet/diaper, lower stimulation, and one familiar activity.', avoid: 'Do not over-schedule the entire window or introduce several unfamiliar activities.', finish: 'Tidy one activity, share the important handoff details, and return to the normal family routine.' },
};

const durationMinutes: Record<string, number> = { '5 min': 5, '10 min': 10, '30 min': 30, '1 hour': 60, 'A few hours': 180, 'All afternoon': 240 };
const ageLabel: Record<CareAge, string> = { baby: 'baby', toddler: 'toddler', preschool: 'preschooler', bigkid: 'school-age child', tween: 'tween', multiple: 'children' };

export function buildCaregiverPlan(input: { age: CareAge; time: string; situation: string; energy: CareEnergy; childName?: string; traits?: string[]; whatWorks?: string; enjoys?: string }): CaregiverPlan {
  const scenario = scenarios[input.situation] ?? scenarios['just-a-plan'];
  const minutes = durationMinutes[input.time] ?? 30;
  const band = input.age === 'baby' ? 'baby' : input.age === 'multiple' ? 'multiple' : input.age === 'toddler' || input.age === 'preschool' ? 'little' : 'older';
  const activityCount = minutes <= 10 ? 1 : minutes <= 60 ? 2 : scenario.activities[band].length;
  const steps = scenario.activities[band].slice(0, activityCount);
  if (minutes >= 60) steps.push('Add food, diaper/toilet, or rest at the next natural break; do not stretch one activity across the whole window.');
  if (minutes >= 180) steps.push('Plan a second distinct block after food/rest and leave 15–30 minutes for quiet decompression.');
  if (input.energy === 'exhausted') steps.unshift('Choose the seated, nearby, lowest-setup version and use a timer; good-enough care is the goal.');
  else if (input.energy === 'high' && input.situation !== 'quiet' && input.situation !== 'bedtime' && input.situation !== 'meltdown') steps.unshift('Use your energy for setup or active connection now, then step back when the activity is working.');

  const traits = input.traits ?? [];
  if (traits.includes('sensitive') || traits.includes('slow-to-warm-up')) steps.push('Keep stimulation low, preview changes, and allow extra time before expecting participation.');
  if (traits.includes('very-active') && !['quiet', 'bedtime', 'meltdown'].includes(input.situation)) steps.push('Include purposeful movement before asking for sitting or waiting.');
  if (traits.includes('strong-willed') || traits.includes('independent')) steps.push('Offer two acceptable choices and give them ownership of one job.');
  if (input.whatWorks?.trim()) steps.push(`Use what the family says usually works: ${input.whatWorks.trim()}.`);
  else if (input.enjoys?.trim() && ['bored', 'quiet', 'independent', 'one-on-one'].includes(input.situation)) steps.push(`When possible, connect the activity to this interest: ${input.enjoys.trim()}.`);

  const energyText = input.energy === 'exhausted' ? 'low-energy' : input.energy === 'some' ? 'moderate-energy' : 'higher-energy';
  return {
    title: scenario.title,
    context: `${input.time} · ${energyText} · ${ageLabel[input.age]}`,
    doThisFirst: scenario.immediate,
    whatToSay: scenario.say,
    timelineLabel: minutes <= 10 ? `FOR THE NEXT ${minutes} MINUTES` : minutes === 30 ? 'FOR THE NEXT 30 MINUTES' : minutes === 60 ? 'FOR THE NEXT HOUR' : input.time.toUpperCase(),
    steps,
    planB: scenario.planB,
    avoid: scenario.avoid,
    finish: scenario.finish,
    childNote: input.childName ? `For ${input.childName}${traits.length ? ` · temperament: ${traits.join(', ')}` : ''}` : undefined,
  };
}
